services:
  nginx:
    image: nginx:alpine
    ports:
      - "81:81"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - frontend
      - backend

  backend:
    build: 
      context: ./backend
      platforms:
        - linux/amd64
    expose:
      - "8000"
    environment:
      - DATABASE_URL=postgresql://postgres:password@db:5432/hr_admin
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
      - TELEGRAM_CHAT_ID=${TELEGRAM_CHAT_ID}
      - NOTION_TOKEN=${NOTION_TOKEN}
      - NOTION_DATABASE_ID=${NOTION_DATABASE_ID}
      - NOTION_TASKS_DATABASE_ID=${NOTION_TASKS_DATABASE_ID}
      - FRONTEND_URL=http://localhost:3000
    depends_on:
      - db
    volumes:
      - ./backend:/app
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload

  frontend:
    build: 
      context: ./frontend
      platforms:
        - linux/amd64
    expose:
      - "3000"
    environment:
      - REACT_APP_API_URL=http://backend:8000
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend

  db:
    image: postgres:13
    environment:
      - POSTGRES_DB=hr_admin
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: 