version: '3.8'

services:
  # База данных PostgreSQL (для продакшена используем внешнюю БД)
  # db:
  #   image: postgres:15-alpine
  #   environment:
  #     POSTGRES_DB: hr_admin
  #     POSTGRES_USER: postgres
  #     POSTGRES_PASSWORD: password
  #   volumes:
  #     - postgres_data:/var/lib/postgresql/data

  # Бэкенд API
  backend:
    build: ./backend
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - SECRET_KEY=${SECRET_KEY}
      - BOT_TOKEN=${BOT_TOKEN}
    ports:
      - "8000:8000"
    # depends_on:
    #   - db
    command: >
      sh -c "
        python init_heroku_db.py &&
        uvicorn main:app --host 0.0.0.0 --port 8000
      "

  # Фронтенд React (сборка для продакшена)
  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    environment:
      - REACT_APP_API_URL=${REACT_APP_API_URL:-http://localhost:8000}
    ports:
      - "3000:3000"
    depends_on:
      - backend

  # Nginx для проксирования
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - frontend
      - backend

# volumes:
#   postgres_data: 